export const appication = {
    appname: "FastSave",
    apphost: "http://localhost:3000",
    locales: [
        "en",
        "id",
        "vi",
        "ms",
        "jv",
        "es",
        "de",
        "fr",
        "it",
        "ko",
        "pt",
        "ru",
        "ja",
        "pl",
        "tr",
        "th",
        "hu",
        "cs",
        "nl",
        "el",
        "hi",
        "uk",
        "ro",
        "zh",
        "zh-TW",
    ],
};
